{% set name = "gaze" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wtetsu/gaze/archive/v{{ version }}.tar.gz
  sha256: d5aec83c31e892acb8ee2c2e04a80d4a465ef76253391d4047b9de161b869868

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - gaze --help

about:
  home: https://github.com/whetsu/gaze
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Execute commands for you
  dev_url: https://github.com/whetsu/gaze

extra:
  recipe-maintainers:
    - danielnachun
